= ALLI MOLTO ILLUSTRI SIGNORI MIEI OSSERVANDISSIMI

== LI SIGNORI ACADEMICI FILARMONICI

E al solo rispetto della mia divitione, & de i miei oblighi con le Signorie Vostre io havessi havuto riguardo,
una certamente delle primse cose, ch'io havessi fatto mai, sarebbe stata questa, laquale hora è, se non ultimo
almeno tardissima, cioè il dedicar loro qualche fatica mia; & con questo mezzo forse debole, ma però a loro
conveniente, & a me non improprio, non tanto dichiarare l'affetto mio verso le Signorie vostre, quanto
dar qualche gratitudine a gli effetti loro verso di me. Ma non mi è parso mai di conceder tanta libertà a questo
mio compiacimento, ancor che legitime, che non habbi riserbato a me sempre il pensare, che le cose buone
vogliono esser fatte bene; altramente, che non riescono tali: Et però sono andato aspettando di venire a 
quest'atto sin' a tanto, che ho creduto di poterlo fare; non già bene del tutto, come sarebbe convenuto al
merito loro, & come io havrei desiderato; ma o con piu maturità, o con manco imperfettione, che non havrei fatto in altro tempo per lo
passato, con la qual ragione haverà da difendermi per aventura havesse alle volte preso maraviglia nel vedermi cosi trascurato
con Persone, con le quali io ho oblighi, & interessi cosi principali, & cosi noti, come ho con loro, poiche; oltre al rispetto della
commune Patria; la quale per se honoratissima, tanto piu m'obliga alle Signorie vostre, quanto elle è piu honorata, & piu riguardevole
per cagione della virtù loro; & oltre a quella protettione, & honore, che da cotesta sempre nobilissima, Academia sono usciti
di continuo così generosamente verso la Musica, & i Professori di quella; io particolarmente sono stato di esse, & in universale, &
in privato favorito, & beneficato in ogni tempo per modo tale, che posso dire, che nelle loro volontà, & operatione verso di me io ho
trovato mescolati sempre questi due sensi di Padroni, & di Padri con una perpetua carità. Hor io protesto, che con la presente mia
attione altro non pretendo, che mostrar loro nel miglior modo, che mi è possibile, affetto, devotione, & gratitudine: & le giuro, che se
ciò conseguo, pongo per benissimo speso tutto il tempo, che io ho consumato sin qui per poter pagare questo debito con moneta men
cattiva: Et perciò le supplico, che nel ricevere queste compositioni, quali si siano, elle vogliano sopra ogni cosa considerare questa
intentione, questa gradire, & col testimonio di questa rendersi certe di non poter haver mai Servitore ne piu obligato di me, ne piu
desideroso di servirle: Et baciandole con riverenza le mani, prego loro dal Signore ogni piu vera prosperità.

Di Cremona in dì 27. Novembre 1587.

Delle SS. VV. Molto Illustri

Obligatissimo Servitore

Marc' Antonio Ingegneri.
