= To the Most Illustrious Sir Don Pompeo dalla Noia,

== My Lord and Most Respected Patron,

Of the wise Chilon of Lacedonia, one of the Seven Sages of Greece,
as wont to say that one should always remember and never forget the
benefits received from others, as forgetting them is a sign of
ingratitude. Therefore, in order not to fall into this error and
having received many notable favors from Your Illustriousness, for
which I am infinitely indebted, and not having any other way to acknowledge 
my appreciation, I have composed some songs on various subjects and I think
it is appropriate to dedicate them to your Illustrious name before anyone
else, not as something worthy of you, but to reveal my gratitude and
my desire to always serve you faithfully, loving and honoring you. Will
your Illustriousness deign to accept them as the first fruits, not yet
fully ripe, of my small garden, with that humanity that, in addition to
many other virtues, makes you dear to everyone. I promise that if a more
favorable season is granted to me, I will make you a part of more ripe
and tasty fruits. In the meantime, I will pray to our Lord God that He
gives you long life and happiness.

From Your Most Illustrious Excellency's

Devoted Servant

Il Sessa D'Aranda.

