= ALLO ILLUSTRISSIMO SIGNOR DON POMPEO DALLA NOIA

== SIGNOR ET PATRONE OSSERVANDISSIMO

Al Sapientissimo Chilone di Lacedomonia, il quale fu uno delle Sette 
Sapienti della Grecia, soleva dire Illustrissimo Signor che colui, il quale riceveva da alcuno
qualche beneficio, lo doveva sempre tenere nella memoria: ne mai se lo doveva scordare: imperoche
il scordarsi del beneficio ricevuto è segno veramente di ingratitudine. Laonde io per
non cascare in questo sì brutto errore: havendo da V. S. Illustriss. ricevuti molti signalati
favori, per li quali ne le tengo infinito obligo: & non havendo altro modo di poterle
mostrare quanto sia di ciò ricordevole: havendo gli anni passati composto alcuni
Canti sopra varii soggetti: ho riputato esser ben fato, se tali quali elli siano, li dedicasse
al nome suo Illustriss. prima ch'ad ogn' altra persona, non già come cosa degna di lei:
ma per scoprirle con questo picciolo segno quant'obligo le tenga: & quanto desidero di sempre
servirla fedelmente, amandola & honorandola. Si degnerà adunque V. S. Illustriss: accettarli come
primi frutti, non ancora ben maturi del mio picciolo giardino, con quella humanità, con la quale:
oltra tante, altre virtù, che un tale adorna; la rende ad ogn'uno caro: promettendole,
che se alcuna più propicia estate mi concederà, che ne nascano di più maturi & più saporosi:
ch'io ne la farò partecipe. Et fra tanto pregherò il nostro Signor Dio che le dia lunga vita & 
felicità.

Di V. S. Illustriss:

Devotissimo Servitore

Il Sessa D'Aranda.
