#!/bin/bash

alessandro_raverii/canzoni_per_sonare/single-parts/01-gabrieli-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/02-gabrieli-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/03-gabrieli-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/04-gabrieli-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/05-merulo-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/06-guami-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/07-maschera-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/08-maschera-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/09-antegnti-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/10-luzzaschi-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/11-lappi-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/12-lappi-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/13-frescobaldi-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/14-grillo-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/15-grillo-a4-0-score.ly
alessandro_raverii/canzoni_per_sonare/single-parts/16-grillo-a4-0-score.ly


florentio_maschera/libro_primo_de_canzoni/single-parts/01-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/02-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/03-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/04-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/05-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/06-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/07-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/08-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/09-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/10-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/11-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/12-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/13-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/14-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/15-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/16-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/17-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/18-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/19-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/20-canzon-a4-0-score.ly
florentio_maschera/libro_primo_de_canzoni/single-parts/21-canzon-a4-0-score.ly

floriano_canale/canzoni_da_sonare/single-parts/01-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/02-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/03-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/04-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/05-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/06-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/07-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/08-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/09-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/10-canale-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/11-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/12-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/13-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/14-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/15-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/16-canzon-a4-0-score.ly
floriano_canale/canzoni_da_sonare/single-parts/17-canzon-a4-0-score.ly

./adriano_banchieri/canzoni_alla_francese/single-parts/01-banchieri-a4-0-score.ly
./adriano_banchieri/canzoni_alla_francese/single-parts/06-banchieri-a4-0-score.ly
./agostino_soderini/canzoni/single-parts/01-soderini-a4-0-score.ly
./antonio_mortaro/primo_libro_de_canzoni/single-parts/01-mortaro-a4-0-score.ly
./antonio_mortaro/primo_libro_de_canzoni/single-parts/02-mortaro-a4-0-score.ly
./antonio_mortaro/primo_libro_de_canzoni/single-parts/03-mortaro-a4-0-score.ly
./antonio_mortaro/primo_libro_de_canzoni/single-parts/05-mortaro-a4-0-score.ly
./antonio_mortaro/primo_libro_de_canzoni/single-parts/20-mortaro-a4-0-score.ly
./di_diversi/1617__seconda_aggiunta_alli_concerti/single-parts/01-pellegrini-a4-0-score.ly
./di_diversi/1617__seconda_aggiunta_alli_concerti/single-parts/03-cima-a4-0-score.ly
./francesco_usper/ricercari_et_arie_francesi/single-parts/15-usper-a4-0-score.ly
./gioseffo_guami/partidura_per_sonare_della_canzonette_alla_francese/single-parts/01-guami-a2-0-score.ly
./giovanni_cavaccio/musica_a_4/single-parts/01-cavaccio-a4-0-score.ly
./giovanni_cavaccio/musica_a_4/single-parts/02-cavaccio-a4-0-score.ly
./giovanni_domenico_rognoni_taeggio/canzoni/single-parts/01-rognoni-a4-0-score.ly
./girolamo_frescobaldi/recercari_et_canzoni/single-parts/01-frescobaldi-a4-0-keyboard_score.ly
./girolamo_frescobaldi/recercari_et_canzoni/single-parts/01-frescobaldi-a4-0-score.ly
./johann_staden/newe_pavenen_galliarden/single-parts/29-staden-a4-0-score.ly
./marc_antonio_ingegnieri/il_secondo_libro_de_madrigali_a_4/single-parts/20-ingegnieri-a4-0-score.ly
./marc_antonio_ingegnieri/il_secondo_libro_de_madrigali_a_4/single-parts/21-ingegnieri-a4-0-score.ly
./salamone_rossi/il_secondo_libro_delle_sinfonie/single-parts/33-rossi-a4-0-score.ly

