= AL SERENISSIMO SIGNOR

== DON VINCENZO GONZAGA

== Duca Di Mantova, & di Monserrato.

Serenissimo Signore, mio Signore, & Patrone colendissimo.

Quando alli dì  passati V.A. si degnò di udir cantare alcuni pochi
Balletti, ch'io havena all'hora composti; mi fu detto che havrebbe
havuto caro ch'io ne facessi de gli altri, quasi mostrando
che quelli le fussero piacciuti: On'dio bramoso di farle cosa grata,
stimando che'l suo desiderio mi fosse commandamento, ne feci
tanti, quanti credei che con già bastassero a formarne un
convenevole volume. Et questo quale egli si sia viene hora
arditamente a riconoscere chi gli ha dato lo spirito, che in somma è
V.A. senza di cui egli non sarebbe in vita; Et per accompagnare
la stagione, & le varie occasioni di noze, & di spattacoli publichi, 
& di balli che s'apprecchiano; questi Balletti tutti festeggianti, & gioiosi, si presentano
a V.A. col rappresentarle insieme la molta divotione del loro Autore, & l'allegrezza che sentono,
di doverla non spiacevolmente trattenere. Segnisi V.A. per l'usata sua benignita di gradir
l'uno, & gli altri, & se non per merito loro debolissimo, o nullo, almeno perché diversamente
da gli altri balli questi si saranno sentire nel ballo, & mirare nel canto, & alla felice gratia di
V.A. humilissimante mi raccomando. Di Matova [sic] il dì Febraro 1591.

Di V. A. Serenissima

Humilissimo Servitore

Gio. Giacomo Gastoldi.

