= ALL'ILLUSTRISS. ET ECCELL.

== SIGNOR PATRON MIO SINGULARISS

=== IL SIG. DON VIRGINIO ORSINO

==== Duca di Bracciano.

Havend'io à far comparire in publico le presenti mie compositioni,
hò preso ardire d'honorarle del nome suo, del qual'io son 
solito d'honorar me, & tutte le cose mie, non havend'io protettion più
certa che di V. Eccell. ne più dolce, & grato rifugio, che la
sua felicissima ombra in ogni mio accidente. La supplico adunque
on ogni affetto, & reverenza, che si degni far cortese accoglienza
à queste mie timide Muse, acciò che col suo applauso siano anco ricevute,
& gradite volentieri dal Mondo, & assicurate dal sincero
giuditio di V. Eccell. (la qual è hoggi principale, anzi unico intelligente, & protettore
di questa & d'ogni altra virtù) non s'habbiano à vergognare di comprarire dinanzi à gl'altri.
Oltra che per essere nate, & nudrite in casa sua, non conoscano altro Signore, & io
col mezzo loro, & di questa breve lettera rinfrescando la memoria della mia devotione,
prego all'Eccellenza Vostra longa & felicissima vita. 

Di Roma il di 1. Genaro 1591.

Di V. Eccell. Illustriss.

Devotiss. & Obligatiss. Ser.

Luca Marenzio.
