= TO THE MOST ILLUSTRIOUS AND MOST REVEREND

== MY MOST HONORABLE PATRON

=== SIGNORE CINZIO ALDOBRANDINI.

=== Cardinal of San Giorio.

I confess candidly, that these madrigals, of which ornated by the name
of Your Most Illustrious Worship are now published [released into the light],
are [as much] fruits of my sterile art as of your fertile kindness: thus my
spirit, woken by the continuous favors you make for me, and illuminated by
the clarity of Your Most Illustrious Worship's infinite virtue, for which like
an almost new and splendid Sun is more envied than imitated, goes hand in hand
producing effects not keeping in kind with the virtue that moves it, but according
to the disposition of my imperfection. It is indeed true, that because I
recognized that my servitude did not displease you, I have tried with every
effort (and perhaps in vain) to derive from the Heroic qualities that radiate
from you some perfection in my own works; And if I have not advanced [as much] like
I wished, the abundance of devotion in my soul must compensate for the lack
of excellence in my art. And thus I beseech Your Most Illustrious Worship
accept these efforts of mine (as effects of the numerous graces I have received
from you) be adorned with your most illustrious name, to render me dear to myself,
while with every diligence I will endeavor to show myself not unworthy of that grace,
of which by your own goodness you have demonstrated to me. I humbly kiss your
Illustrious Worship's hands and pray to the Lord God for every greatest prosperity.

From Rome the first day of January, 1594

For Your Most Illustrious and Most Reverend Worship,

Your devoted and most obligated servant

Luca Marenzio
