= ALL'ILLUSTRISS. ET REVERENDISS.

== SIGNOR MIO PATRON COLENDISSIMO

=== IL SIGNORE CINTIO ALDOBRANDINO.

==== Cardinal di San Giorgio.

Io confesso ingenuamente, che questi madrigali, i quali ornati del nome
di V[ostra] S[ignora] Illustriss[ima] escon pur hora in luce, son così frutti del mio
sterile ingegno, come della feconda benignità sua; Percio che l'animo
mio risvegliato da' continui favori che mi fa, & illustrato dal chiaro
dell'infinita virtù di V[ostra] Sig[nora] lllustriss[ima] per la quale quasi nuovo &
splendido Sole è piu tosto invidiata che imitata, va di mano in mano
producendo effetti non conforme alla virtù che lo muove, ma secondo
la disposition del mio imperfetto. Egli è ben vero, che da che io
conobbi che non l'era discara la servitù mia, ho procurato con ogni
industria (e forse indarno) di far derivar dall'Eroiche parti che
risplendono in lei qualche perfettion nelle cose mie; Et s'io non mi ci
sono avanzato, come volevo, doverà supplire l'abbondanza della devotion
dell'animo al mancamento dell'eccellenza dell'arte. Et però supplico
V. Sig. lllustriss. che gradisca che queste mie fatiche (com'effetti
delle tante grazie ch'io riceva da lei) si abbelliscano del chiarissimo
nome suo, per render me più caro a me stesso, mentre con ogni studio
procaccierò di mostrarmi non indegno di quella gratia, della quale per
sua propria bontà m' ha fatto partecipe. Bacio humilmente le mani di
V. Sig. Illustriss. e le prego dal Signor Dio ogni prosperità maggiore.

Di Roma il dì primo Genero 1594.

Di V. Sig. Illustriss. e Reverendiss.

Devotiss. ed obligatiss. servitore

LUCA MARENZIO.
