= AL SERENISSIMO SIGNOR

== ET PATRON MIO

=== IL SIGNOR DUCA DI FERRARA

Se tutte le cose Serenissimo Prencipe desiderano d'unirsi, quanto più possono alla
causa loro, è ben ragione che io consacri a Vostra Altezza questi Madrigali come
a quella che n'è stata la principal cagione, così per havermi raccolto nella sua
Corte nella quale sono huomini famosi & Illustri in questa scienza e nell'altre,
come per havermi favorito in farne cantare la maggior parte di essi, & gratiosamente
udirli; La onde ho preso ardire di porli in luce, Ben è vero ch'io non attribuisco tanto
al mio artifitio quanto alla soavità della voce di quelle Illustre Signore che li cantarno, le quali
con la maravigliosa dispositione, & col nuovo non più inteso modo di passaggi & accenti, che
accrescano assai più facilmente il diletto di questa Musica ch'io non posso la fama di tanto loro
eccellenza, E perché io non so con altri segni di gratitudine manifestare l'obligo infinito ilquali ho
a Vostra Altezza per li favori che da lei ricevo, la priego ch'accetti questo picciolo testimonio
della mia servitù con quella benignità & grandezza d'animo che nell'altre sue attioni è solità
dimostrare. Con che da N.S. gli desidero ogni felicità. Di Ferrara il dì 15. di Settembre 1584.

Di. V. A. Serenissima

Humilissimo Servitore

Paol Virchi.
