= AL SERENISS. SIG. MIO, SIG. ET PADRONE COLENDISS.

== IL SIGNOR DUCA DI FERRARA. &c.

Havrei commesso notabilissimo errore se dovend'io dar in luce questi miei componimenti di Musica fatti
per la maggior parte in Ferrara ad altro personaggio indirizzati gli havessi che à V.A. Percioche a cui 
più degnamente dedicare gli potev'io? Prencipe tanto grande, tanto amico delle vertù, tanto fautore de
vertuosi, & delle cose mie prottetore tanto benigno.  Et essi in qual parte del mondo potrebbon esser meglio cantati
che nella Corte di V.A.? dove io non mi so ben risolvere qual sia maggiore o la maestria di chi canta o’l giudico
di chi l’ascolta. Percioché lasciando stare di tanti altri eccellenti & Musici, & Cantori che sono nella sua
numerosissima e perfettissima Capella: a cui non sono hoggimai note le meraviglie & d’arte, & di natura,
la voce, la gratia, la dispositione, la memoria, & l’altre tante & sì rare qualità delle tre nobilissime giovani
Dame della Serenissima Signora Duchessa di Ferrara? Il qual rispetto per se solo bastar dovrebbe a indurre tutti i compositori del
mondo, che le loro opere indirizzassero a V.A. perché da si divini voci, & da sì sobil concerto ricevessero il vero, & naturale spirito
della Musica. Ma io non m'aveggio che on l'amplificar le cagione che a ciò mi muovono si vien attenuando la dignità dell'opera
mia, come quella che de perfettione all'eccellenza di tanti oggetti non corrisponde. Et però supplico V.A. che non mirando a quel che
ella vale, ma piutosto devotissima intentione di chi la dà, si degni di gradirla benignamente, accioche il mondo sappia, che senza
buona gratia di lei non porta in fronte il Serenissimo nome di V.A. Alla quale humilmente inchinandomi bacio la mano, & prego
Dio per la continua essaltatione, & prosperità sua.

Di. V.A.

Humilissimo & Devotissimo Servitore

Giaches Wert.
