= TO MY MOST SERENE LORD, MY LORD AND MOST RESPECTED PATRON, 

== THE DUKE OF FERRARA, ETC.

I would have committed a quite notable mistake if, when I decided to
publish these musical compositions of mine, composed mostly in Ferrara, had I
addressed them to any other person than Your Excellency. For to whom
could I more properly dedicate them? A prince so great, such a friend to
virtue, so much a patron of the virtuous, and so benevolent a protector
of mine own works. And where in the world could they be better sung than
in Your Excellency's court? Thus I cannot decide which is greater: the
skill of the singer or the judgment of the listener.  Leaving aside the
many other excellent musicians and singers who are in Your Excellency's
numerous and most perfect chapel, who are now familiar with the wonders of
art and nature, the voice, grace, disposition, memory, and so many other
rare qualities of the three most noble young ladies of the Most Serene
Duchess of Ferrara? This respect alone suffices to induce all
composers in the world to direct their works to Your Excellency, so that
they may receive the true, natural spirit of music from such divine
voices and from such a noble concert.  But I fear that by amplifying the
reasons that move me to this, the dignity of my work is diminished,
as it does not correspond to the perfection and excellence of so many
objects. And thus I beg Your Excellency that, not looking at what it is
worth, but rather at the devout intention of the one who gives it, you
would deign to receive it kindly, so that the world know that it does not
bear the most serene name of Your Excellency on its masthead without
your good grace. To whom, humbly bowing, I kiss your hand, and I pray
to God for your continued exaltation and prosperity.

From Your Excellency's

most humble and devoted servant,

Giaches [de] Wert.
