= AL SERENISSIMO SIGNORE, IL SIG. VINCENZO GONZAGO

== DUCA DI MANTOVA E DI MONFERATO [sic]

=== Mio Signo & Patron Colendissimo.

Piacque sempre alli antichi Poeti & Compositori, nel principio dell'opre, & canti suoi, quasi
per divino & favorevol Nume, invocare alcuna delle Muse, & quella, che a punto gli pareva
essere più atta, a porgerli soccorso in simil tempo. Quindi è Sereniss. Sig. che io ad essempio
loro, havendo altre volte nel dar alle Stampe Madrigali, fatta isperienza d'invocare
la virtù d'alcuni Eccelsi spirti, che mi erano come vere, & non imaginarie Muse; mi son
risoluto anco adesso, pormi al tutto sotto l'ombra & protettione di V.A. & a lei senza più,
mia soblime Musica, consagrar anco questa mia nova Copia de Madrigali; giudicando che
se nelle altre mie fatiche, ella mi fu insieme con quelli Heroi a chi le dedicai, in qualche parte
favorevole; hora saldamente debba sperare, che dedicandole questa, come a mio singolarissimo Signore, & 
(siami lecito così dire) in terra propitio Nume, me ne siano per avvernire, novi favori & gratie, atte in ogni
guisa, ad esaltare questo mio novo parto, quale per fine di questa, tutto pieno di gioia, presentando a V.A. a lei
parimente faccio humilissima riverenza. Di Venetia dì primo Genaro 1588.

Di V.A.

Humiliss. & Devotiss. Servitore

Giaches Wert.
