= AL MOLTO MAGNIFICO MESSER ANTONIO

== MOLTO MIO SIGNOR OSSERVANDISSIMO

Suole communemente avvenire che gli huomini giungendo alla vecchiezza con le forze
del corp vengano ancho perdendo quella vivacità di spirito, che prima dalla natura
era lor concessa, Ma voi signor mio, con maravigliosa virtù, superando la gravezza de
gli anni, havete in ogni tempo felicemente accresciuto nuovo vigore al nobilissimo ingegno
vostro, come hora (oltra, i, olti altri segni) dalle cose della Musica evidentemente
appare, nelle quali siete in pochi mesi divenunto tale, ch'ognum vi ammira per gli
rari frutti, ch'in questa etade si veggono uscir dal vostro divino intelletto, nel quale
specchiandosi gli animi virtuosi, pare, che si come il Sole col calor de raggi suoi trahe
dalla terra tanta varietà di cose, Voi parimente co i raggi della vostro virtù caviate
da gli ingegni loro larga, & diversa copia di pretiosi frutti, come anco di me nelle presenti compositioni è
avenuto, in cui niuna cosa ha potuto più di quel lume, col quale dalla molta vostra virtù, bontà &
liberalità sono stato acceso. Ond'e ragionevole c'havendo esse il lor principio ricevuto da voi, che vostre
parimente siano, si come ancora a voi, per quello ch'a me si ricchiede, si convengono, & per gli infiniti oblighi, ch'io
vi tengo, & per quel particolar debito, c'hanno tutti gli acquisti del figliuolo parmiente al Padre, nel qual
grado siete da ogni virtuoso meritamente tenuto, & riverito. Graditele dunque quali sono, & me tenete vivo
nella gratia nostra.

Di V. S.

Servitore obligato

Andrea Gabrieli.
