= ALL'ILLUSTRISSIMO
= ET ECCELLENTISSIMO

== SIGNORE PATRON MIO

Colendissimo

== IL SIGNORE MARCHESE DI PISANI

Cavalliere de gli Ordini del Re Christianissimo, Consegliero de stati,
& Ambasciatore di sua Maestà.

IL ritorno di Vostra eccellenza è stato universalmente a tutti così grato, &
ha dimostrato ogn'uno in particolare di senirne tanto contento, che s'io
(che come devotissimo servitore suo ne ho sentita somma allegrezza)
non ne dessi qualche segno a lei, & al mondo insieme, mi parrebbe di 
mancar molto & a me stesso, & al debito della servitù mia. Desideroso
dunque di sodisfar almeno in qualche parte all'animo mio, ho deliberato
(già che a me non è permesso il far'altra dimostratione) di dedicare a lei queste mie poche compositioni di musica, sperando ch'ella non solo, come fautrice che è di questa virtù, debba (quali elle si siano) haverle care, ma che tanto di forza, & rigore prenderanno dallo
splendore del suo nome, sotto il quale escono in luce, che per ciò potranno irsene altiere
gloriandosi fra se medesime d'esser raccommandate alla protettione d'un tanto Prencipe,
l'ombra sola del quale sarà bastante a coprire ogni loro imperfettione. Degnisi ella però
d'accettar da ma questo picciol dono, & di gradire l'affetto, & devotione mia verso di
lei, conservandomi nella sua gratia, che s'io giongo ad ottener questo (come spero) non solo
terrò per ben'impiegate queste mie fatiche, ma giudicarò insieme d'haver conseguito
il fine di tutti i miei più nobili pensieri. Con che resto baciando a Vostra Eccellenza humilissimamente le mani, & pregando il Signore Iddio che le conceda quelle prosperità
maggiori, ch'ella stessa desidera. Di Roma alli x. Decembre. MDLXXXVI.

Di Vostra Eccellenza

Humilissimo, & devotissimo Scrivatore

Luca Marentio.
