= TO MY ILLUSTRIOUS
= AND MOST EXCELLENT

== LORD

The Most Honorable

== THE MARQUEE OF PISANI

Knight of the Order of the Most Christion King, Councillor of state,
& ambassador of his Majesty.

The return of your excellency has been universally most welcome to all, &
has shown to everyone such contentment, that should I (who as your most devoted
servant who has also felt the utmost joy) not give some sign of it to you, and 
to the world in general, it should seemingly fail both to myself and to the debt that I owe in my servitude. Desiring thus to satisfy at least some part of my
mind, I resolved (since I have already not allowed myself to make further show)
to dedicate these my few musical compositions to you, hoping that not only,
as a patron of this art, you would (as they were) receive them so that they
will gain strength and rigor from the splendor of your name, under which
they will be published ['brought into the light'], so thus they would be able to take the highest glory
by being recommended due to the protection of such a Prince, whose shadow
alone will be sufficient to overcome any of their imperfections. Deign, thus,
to accept from me this small gift, and with gratitude my affection &
devotion to you, keeping me in your grace, that if I manage to obtain
this (as I hope), not only will I consider my labors well-employed, but
I will judge at the same time having achieved the fulfillment of my
noblest ambitions. With that I remain mostly humbly kissing your
Excellency's hands, & praying the Lord God grant that greatest
properity, that you yourself desire. From Rome, 10 December, 1586.

From your Excellency's

Most supremely humble and most devoted scribe,

Luca Marenzio
