= ALL'ILLUSTRmo ET REVERmo SIGor

== PATRON MIO COLENDISSIMO

=== MONSIGNOR LUIGI GALLO

Non potevo io con più viva e più efficace dimostratione
rapresentare a Vostra Signoria Illustrissima quell'osservanza
con la quale mi pregio di viverle servitore, che
con gl'istessi parti quali elli si siano del mio ingegno Poiche
ritenendo essi in se qualche sembianza di chi diede
loro l'essere, & uscendo hora al Mondo sotto la protetione
sua, verranno insieme a palesare altrui, quale io mi viva di devotione
non ordinaria verso la persona di V.S. Illus. La singolare sua benignità e 
l'altre sue doti consciute gia e celebrate universalmente da ogn'uno, la
rendono amabile anche da quelli che di presenza non la conoscono Io che mi vedo
da lei favorito con straordinario affetto in tutto ciò ch'il Signor Dio m'ha
dato di talento nella mia professione ho tanto maggior cagione di riverirla
e di servirla sempre, quanto son più particolari gl'effetti che mi vengono
dalla sua bontà. M'è parso però mio debito con questi Madrigali dedicarlemi
perpetuo & obbligatissimo servitore supplicandola a gradire il dono che le
esibisco cosi dell'Opera come di me stesso, & a continuarmi la sua solita
protettione mentre con augurarle essaltatione e felicità corrispondente al suo
merito e valore, le faccio humilmente riverenza e bacio le mani.

Di Loretto li 25 di Febraro 1615

Di. V. S. Illust. & Reverendiss.

Obligatissimo Servitore

Antonio Cifra

