= ALL' ILLUSTRISSIMO 

== mio Signore & Padrone osservandissimo, 

== IL SIGNOR CONTE MARIO BEVILACQUA.

Si rimette il peccato, Illustrissimo Signor Conte (lo concedono le leggi,
com' ella sà meglio di me) ogni volta che si rende il tolto. Sottrassi a
i giorni passati, poi che più volte mi s' oppose la loro volontà, dalle
mani de i SS. Conti Bonifatio, & Luigi Bevilacqui i presenti Madrigali,
i quali insieme con altri molti havevano raccolti in poco spatio di tempo
da diversi Auttori per pascerne virtuosamente il loro floridissimo &
nobilissimo ridotto; li rendo hora a V. S. Illustrissima congionta
ad essi SS. non solo di legame di parentela, ma insieme di reciproca
affettione; a V. S. dico, uno de principali lumi al presente di questa
Nobilissima Fameglia, dalla quale sono discesi per lo spatio di più di
cinquecento anni ch' ella venne in Italia tanti valorosi soldati, Illustri
Capitani, dotti Prelati, huomini famosi di governo e di stato, fregiati
da Papi, Imperatori & Duchi con Honorati tituli di Cavalieri, Conti,
e Marchesi, e riconosciuti anticamente con molti feudi e giurisditioni
di mero & misto imperio, & amplissimi privilegij. Crederò con questo
haver cagionato multi buoni effetti; dilettato a lei co 'l presentarli
così vago dono; sodisfatto a SS. Conti suoi Parenti nel restituire
a V. S. il tolto a loro; compiacciuto al mondo facendole copia di
così ricco thesoro; & finalmente satiato l' ardente voluntà mia di
discovrirle un giorno parte della divotione dell' animo mio, & prender
occasione di farmele conoscere effettualmente per quello affettionato
servitore, che buon pezzo fà vivo obligato alla sua gloriosa fama,
& immortale. V. S. Illustrissima ricevi in se il diletto di lei; la
sodisfattione de i detti SS. Conti; l' applauso del Mondo, & la divota
volontà mia, & mi facci parte della gratia sua, ch' io con la debita
riverenza le bacio le mani, & la desidero felice corso a gli honorati
suoi pensieri.  

Di Ferrara il dì ultimo di febraio 1592.

Di. V.S. Illustrissima

Affettionatissimo Servitore

Filippo Niocoletti.
