= AL MOLTO MAGNIFICO SIGNOR

== BENVENUTO RISALITI

=== Luocotenente dell'Eccellente Signor Giovanni Bonori+
Regio Percettore della Provincia di+
terra d'Otranto.

==== Signore mio osservandissimo.

NON è dubbio, che molti troppo pronti censori dell'altrui cose, non
habbino d'haver meraviglia, e forse a male, ch'io habbia voluto a V.S.
più presto drizzar la presente opra, che ad alcun gran Prencipe o
Signore d'Italia, e tocchi per aventura da invidia tal proponimento
cercaranno biasimare; Ma se vuoti d'ogni passione, vogliam por
mente a tutte le fattiche di quei illustri antichi scrittori; che d'ogni
sapere furono Erarii, e Maestri: scorgeremo la maggior parte di quelle
i loro Autori non haver dedicate a Re, Imperadori, o altri gran
Personaggi, ma loro cari amici, e discepoli, havendo havuto l'occhio
non a i disegni della mondana pompa, e gloria, ma solo a far partecipi de i loro Thesori quei,
che per l'amore, che alle virtu portavano, n'eran degni, & anco utili conservatori, e non coloro,
che per beni di Fortuna più si pregiavano. Con ragione ho voluto donque io moss oda una
sincera, e pura volontà di questo parto del mio ingegno far a V.S. un libero dono, poi che io non
veggio persona a cui la Musica, e per meritodi virtù, e per amor, che le portate debbia essere
più obligata. Oltre di ciò per esser lei molto affectionata d'essa Musica, della quale in Prattica
gentilmente discorre, saprà, e potrà da i morsi degl'inuidiosi sicuramente difendermi, per cioche
s'eglino hanno ardire di lacerare, e schernire il vero padre della Musica Adriano, e con lui
Cipriano, dei quali io sono indegno discepulo, che saranno di queste mie povere compositioni?
Ma perche fempre la virtù fa a se stessa lume co i raggi del proprio splendore, e non co'l fumo
dell'humane grandezze, raccomendarò i miei scritti a quella: che da i savi di Persia fu
reputata la più potente di tutte le cose, dico alla verità. E con ciò à V.S. bacio la mano.

Da Venetia il dì 15. di Marzo. MDLXXVII.

D.V. S.

Affettionatissimo Servitore.

Alessandro Romane.

