= AL MOLTO MAG. ET NOBILISS. SIGNOR

== IL SIGNOR GIOVANNI SARACINI.

=== MIO SIGNO ET PATRON OSSERVANDISS.

\[MARK\]

TANT'E la servitù e viverentia, ch'io porto a V.S. che stimerei grandemente
offender me stesso, se queste mie fatiche, così per rispetto
mio, come dell'istesse compositioni non havessi dedicato al Nobilissimo &
vertuosissimo nome suo. Il rispetto che tocca a me è di publicarme
al Mondo, per quel affettionato Servitore, ch'io veramente le sono, 
Et perche se sappi, che se la mia tenuefortuna mi toglie quelle
segnalate occasioni, con le quali più volentieri vorrei poter mostrare
l'affettionato & riverente animo mio, verso di cosi honorato mio Signore, che
almeno in quel poco ch'io posso me le dimostro, come veramente le sono
affettionatiss. & obligatiss. Servitore. Quel che m'ha mosso per rispetto
delle compositioni a divernire in questa opinione è anch'egli per se
stesso palese, perchio che tra l'altre tante vertù, che risplendono in V.S.
ell'è anco intendentissima della Musica, come quella che non ha lasciat'a dietro niuna eccellente & rare vertù.
Laonde non potevano esse compositioni con maggio authorità, ne 
sotto più forte & saldo scudo comparire, che sotto il preggiato & non mai a
bastanza lodato nome di V.S. La prego adunque, che si com'è ben proportionate
con la servitù mia, & con il valor suo il mio pensiero, cosi V.S. si desgni
benignamente raccoglierlo, accettando benignamente nella sua prottetione questo
frutto della mia servitù, e conservarmi nell'usata sua buona gratia,
nella quale di core me le raccomando pregandole il colmo d'ogni felicità.

Affettionatiss. & obligatiss. Servitore di V.S.

Andrea Gabrieli.
