= ALL'ILLUSTRISS.MO SIGNORE

== HIPPOLITO BENTIVOGLIO

=== Marchese di Castel Gualtieri, Signor di Magliano, Conte d'Antignano, et Capitan Generale del Sereniss. Sign. Duca di Ferrara, et mio Signore.

La prima delle cinque figliuole (Signor Illustrissimo) ch'è piaciuto
alla bontà di Dio di donarmi portò con lei dall' alvo materno un'
istinto naturale di servire a sua diuina Maestà: Onde procurai per
quanto s'estesero le forze mie di fare, che ella fosse più adorna
che fù possibile di ogni virtù christiana, et fra l'altre gli feci
insegnare vn poco di Musica sotto la disciplina del famoso Alessandro
Milleuille, huomo al suo tempo d'ogni honorata qualità dotato, come
in quella facoltà Eccellente, e dopò da messer Hercole Pasquino,
et auuenne che imparando questa, sempre presente v' era la seconda mia
figliuola et sua sorella Vittoria detta (bambina di quattro in cinque
anni) la quale affissando la pura mente a i precetti del Maestro che
insegnaua all' altra, apprese tanto, che (non se n'auedendo alcuno)
in termine d' un anno la natura gli slegò in modo le pargolette mani,
che su l' Arpicordo ella cominciò a sonare in modo, che fece stupire
non solo sua madre et me, ma l' istesso precettore ancora. Il qual buon
vecchio si pose ad insegnarli con tanto amore, che in due anni ella fece
profitto grandissimo: onde egli mi pregò aftettuosissimamente che la
facessi alleuare (come feci) nel Monastero delle non mai abbastanza lodate
Mad. Reu. di S. Vito qui in Ferrara, la perfettione et Eccellenza delle
quali nella Musica trapassa (come sà V. S. Illustriss. et come sà tutto
il mondo) tutti gli Concerti più famosi, che dal sesso feminile si siano
sentiti da gran tempo in qua. Onde auenne che questa figliuola giunta all'
età di quattordeci anni prudentemente fece ellettione di quiui anco lei
dedicarsi al servitio di Dio persuasa dal già Reverendiss. Monsig. Paolo
Leoni Vescouo di Ferrara, il quale molto particolarmente amò questo
Monastero per le rare qualità sue: et vedendo io quanto ella s'affaticava
nella Theorica della Musica, feci opera d' hauer alcuni Madrigali del
Molto Illustre et Eccellentiss. Caualiere Guarini in cui si veggono
risplendere tutte le virtuose et honorate qualità: et ella vi fece
sopra la Musica, la quale, essendomi stata più volte lodata da diversi
bellissimi ingegni, ne donai vna copia all' Illustriss. Sign. Conte del
Zaffo la Settimana Santa li mesi passati, mentre egli era in questa
città alloggiato in casa di V. S. Illustriss. Onde ritornato questo
Gentilhuomo à Venetia sua patria, a compiacciutosi di quest' opera
assai, ha cortesissimamente, com'è proprio di lui, voluto fauorire et
honorare le virtù di questa figliuola, con dare l' opera alle stampe,
scriuendo a lei che si compiacesse di dedicarla à chi più gli paresse
meriteuole. et ella che delle cose del Mondo più non cura ha rimesso
ciò in me suo padre. Io che non mi sento più obligato a nissuna casa
che à quella di V. S. Illustriss. et in particolare alla grand'anima
del già Illustriss. Sign. Suo Padre, et à lei, hò giudicato debito
mio il confidare, ch' ella comparisca nel gran Theatro del mondo sotto
la protettione sua, parendomi non poterle ritrovar maggiore scudo in
sua diffesa, nè chi più meriti di essa, nè chi sia più obligato
à seruirla, à riuerirla, et honorarla di me, et di tutta la casa
mia. Degnisi V. S. Illustriss. dunque di fauorirmi, che questa (ben
che piccola) operetta di mia figliuola possa portar segnato in fronte
il nobilissimo, et glorioso nome di lei, et di acettare particolar
protettione dell'autrice, et dell'altre sue sorelle, mie figliuole,
che seruono in detto Monastero à. Dio, ch' elle pregheranno sempre
Sua Diuina Maestà per il felice stato della nobilissima sua Casa, et
in particolare di lei, et io per loro le serò (se però è possibile
esserle più ch' io non sono) obligatissimo.

Di Venetia a li xvi. Giugno MDXCIII

Di V. Sign. Illustriss. 

Obligatiss. & Deuotiss. Seruitore perpetuo

Gio. Battista Aleotti 
d'Argenta.
