= ALL'ILLUSTRISS: ET REVERENDISS:

== SIGNORE, MIO SIGNORE COLENDISSIMO

=== IL SIGN CAMILLO CAETANO

==== Patriarcha d'Alessandria, &c. 

==== Nuntio di N. Sig. appresso sua Mastrà Cesarea

Parrà forse ad alcuno, che poco convenevole dono io presenti a V. Sig. Illustriss. & Reverendiss. come è questo
mio Libro de Madrigali a Cinque voci; nondimeno dovendo pur questo uscir fuori, & per Quintodecimo
far compagnia a gli altri suoi fratelli, non ho potuto di non mandarlo in luce sotto l'honoratissimo nome
di lei percioché sonandosi questi Madrigali li mesi adietro con le viole da gamba, mostrò che piacessero
nobilissime arti, io reputo come patrocinio preso di essi, sotto la cui ombra ardiscano comparire da pertutto.
Per la qual cosa io vengo

Parrà forse ad alcuno che poco convenevole dono io presenti a V. Sig. Illustriss. & Reverendiss. come è questo
mio Libro de Madrigali a Cinque voci nondimeno dovendo pur questo uscir fuori, & per Quintodecimo
far compagnia a gli altri suoi fratelli, non ha potuto di non mandarla in luce sotto l'honoratissimo nome
di lei, percioché sonandosi questi Madrigali li mesi adietro con le viole da gamba, mostrò che piacessero
tanto a V. Sig. Illustriss. che tale giudico fattone da lei, intendentissima cosi di questa come di tutte le altre
nobilissime arti, io reputo come patracinio preso di essi, sotto la cui ombra ardiscano comparire da pertutto.
Per la qual cosa io vengo quasi a presentare a V. Sig. Illustrissima quel che in certo modo, è suo, poi che
dall'auttorità di lei essi sono per ricevere più splendore che dal Componitor istesso. Oltre che io mi conosco si
obligato a V. Sig. Illustriss. per li molti favori, ch'io ogni di recevo da lei da che ha cotesto supremo luogo nella Corte Cesarea, che se io
le presentassi tutto ciò che può venire dal mio ingegno & dalla mia industria, mi parrebbe tuttavia non haver satisfatto a minima
parte dell'obligo ch'io tengo alla sua infinita humanità & cortesia, predicata non pur da me, ma da chiunque la conosce. Onde tanto
maggiormente confido che V. S. Illustriss. accetterà volentieri questo picciol dono verso di se, ma grandissimo s'ella risguarderà la
devotione dell' animo conche l'offero, & pregando Dio per ogni sua prosperità, le bacio humilmente le mani.

Di Venetia il di Primo Maggio 1592.

Di V. Sig. Illustriss. & Reverendiss.

Servitore Deuotiss.

FILIPPO DI MONTE.
