= AL MOLTO MAGco. ET Rdo.

== MONSIGNOR MESIN FORNO

=== Dignissimo Canonico di Modona, mio
=== Signor Colendissimo

IL molto R. Mons: Spirito da Reggio, & l'Eccellente M. Orartio Vecchi, miei singolarissimi
amici, occorrendoci trattare sopra quelli che per la Italia tengono
Virtuoso Ridotto di Musica, mi hanno assai commendato quello di V. S. molto
Reverenda, come quella, che non vere dimostrationi, & gentilissime maniere
accarezza, & fovorisce [SIC] li virtuosi, & massime di tal professione; la qual cosa
ha partorito in me un somma desiderio di farmele conoscere per suo affettionatissimo. Et così per
capara di questo min buon volere, le mando li presenti Madrigali, da diversi Eccellenti Musici
novamente composti, che col mezo della mia stampa hora si lasciano veder in luce. Non le dirò già
che per aventura fossero li più belli, che hoggidì si possino cantare; poi che a questo basterà solo
il valore di chi li ha composti. A me basta dirli, che mi sara favore singolare, se come è solita
volontieri aggradirà questo mio affetto; della qual cosa oltre che son sicurissimo, che questi
honorati virtuosi lodarano cosi nobile elettione, parimente io resterò contentissimo d'haver con questo
mezo acquistata la gratia sua: alla quale basciando le mani, le prego da N.S. Dio ogni suo contento.
Di Venetia il dì primo di Giugno 1585.

Di V. S. Molto Reverenda

Affetionatissimo Servitore

Giacomo Vincenzi.
