= TO THE MOST NOBLE

== and Vertuous Lady, the Lady

=== Arbella Stuart.

==== Madam.

The deepe understanding you have in all the Arts, and
perticular excellency in this of Musicke, doth by a certaine
kind of right, challenge the Dedication of the better
sort of Labours in that Facultie; especially in these
times when Musicke sit solitary among her sister Sciences,
and (but for oyur Honour) often wants the fortune
to be esteemed (for so shee is worthy) even among the worthyest. But
besides that generall right, my true and zealous devotion long since
desirous to expresse it selfe in any humble dutie to your Honour, and borne
up by the daily experience of your most Noble and singular disposition,
hath never thought upon other Patron for this work, then your Honour,
whose never-failing Judgement in the depth of Musicke, I do with might
be pleased with some of these; which happinesse if they attaine, I know
not what judgement can avow to mislike them. Howsoever they behave
themselves, I humbly beseech your Honour, to beleeve this truth; that
they are the sincere oblations of a heart ever prepared for your service.
And so with all humble and due reverence done to your Honour, I beseech
the Almighty to make you in all the passages of your life truely
happy, as you are in the worlds true opinion vertuous.

Your Honours most humbly

devoted and obliged:

JOHN WILBYE.
