= ALL'ILLUSTRISSIMO SIGNOR MIO PATRONE

== OSSERVANDISSIMO, IL SIGNOR ALBERTO

=== ACQUAVIVA D'ARAGONA ET C.

Le molte virtù, c'ho veduto risplendere in V.S. Illustrissima corrispondenti alla sua 
nobilissima casa, & l'honesta, & lodevole delettatione, ch'ella dimostra havere della Musica,
hanno mosso, & acceso l'animo mio di dimostrarle qualche segno dell'affettione, & riverenza
che le porto, in donarle questo piccolo frutto del mio debole ingegno, il quale
se ben conosco che sia poco, o nullo merito, & valore, desiderando pure, quanto per
me si può, recarli luce, ho voluto, che li presenti miei Madrigali, d'ornamento poveri,
& di dolcezza, passino fra le persone col nome di V.S. Illustrissima, la quale essendo per 
lo rispetto di tante sue honorevoli qualità dignissima d'honore, farà servita porre 
queste mie fatiche su'l poggio della sua nobiltà, à fine, che siano per sua cagione almeno 
risguardate, se non havute in pregio, la qual cosa essendo io sicuro di potere promettermi dalla singolare
humanità sua, con tutto il core fo riverenza à V. S. Illustrissima, pregandole sempre felicità.

D.V.S. Illustrissima

Affettionatissimo Servitore

Hippolito Sabino.
