= ALL'ILLUSTRISSIMO ET ECCELLENTISSIMO
= SIGNOR II SIGNOR DONNO ALFONSO 
= DA ESTE PRENCIPE DI FERRARA

Essendo la Musica nova di M. Adriano Willaert nascosta
& sepolta di modo, che alcuno non se ne potea valere, & il mondo
venea a restar privo di così bella compositione, V. Eccellenza tenne
strada questi anni passati, che non solamente l'hebbe, ma ancora fece,
che l'istesso autore la rivide, & corresse molto maturamente, tal
che ogn'uno desidera infinitamente di vederla, altri per pigiarne
dilettatione, & altri per servirsene al comporre; essendo che si può
dire, che nell'essere con buon ordine ridrizzata, habbia havuto il
principio l'accrescimento, & quasi la perfettione ad un tempo medesimo dall'istesso
compositore; & si conosce, che ad ogni sua richesta fa sentir nell'animo tutti gli affetti, che si
propone di muovere, & che è dignissima d'essere imitata. Et perché io so, che per questo
rispetto sarà molto caro a V. Eccellenza, ch'essa a publico beneficio sia posta in luce, havendola
io havuta in dono da lei, ho anchor io voluto pigliar la fatica di publicarla. Et
conoscendo, che uno de maggior Prencipi, & uno de maggior Musici concorrevano in
questa impresa, mi sono ingegnato di fare, che per quanto comportano le mie deboli forze,
la stampa, in qualche parte, loro corrisponda, & tanto più vivamente a ciò mi son mosso,
essendomi l'uno Patrone, & l'altro Maestro. Percioché M. Adriano, per esser non pur rarissimo
in questa arte, ma compiuto nella integrità, con la sua dottrina, & amorevolezza, mi
ha legato a sé d'obligo eterno. & dall'altro canto V. Eccellenza, che per natura sua, con la
grandezza dell'animo, ha sempre accom pagnato la benignità, mi ha raccolto, & avanzato,
assai più, che a miei meriti non si ricerca & perché ella, oltre alle dette ragioni, col suo ottimo
giudicio ha così ben conosciuto il valore di questo divino spirito, che non vi è signore
alcuno, che nella intelligenza della musica la pareggi, come ancora, nelle più importanti
virtù, è al mondo maravigliosa, io ho voluto, che non ad altro personaggio, che a lei sia
fatta questa dedicatione. la quale è il dovere che faccia, che l'opera non conosca altro, che
V. Eccellenza per superiore, poi che tante circonstanze ciò richieggono, che non ve ne
potrebbono essere di vantaggio. & è da tener per fermo, che ella non meno sia per pigliare
il patrocinio d'essa opera a sua conservatione, di quello, che si habbia fatto in darle la vita,
essendo che nel tempo, che era si può dire morta, alcuni sentendo diversi suoi canti, se
ne servirono forse con credere, che il proprio autore non devesse mai esser riscatato dalle
tenebre, ma come la liberalità di V. Eccellenza n'ha ornato il mondo, così ne tal
protettione, che non sarà più da dubitare d'oltraggio alcuno, nome di lei. Nella cui
buona gratia humilissimamente mi raccomando, & prego il Signor Dio per la sua continua
essaltatione & contentezza.  Di Ferrara A 15 di Settembrio. 1558

DI V. ECCELLENZA

Humilissimo & obedientissimo servitore Francesco Viola.
