= ALLA ILLUSTRISSIMA SIGNORA,

== MIA SIGNORA OSSERVANDISSIMA

=== LA SIG. DONNA INES D'ARGOTTI CARRETTA

==== Marchesa di Grana, & Contessa di Milesimo, &c.

Et che cosa direbbe il mondo, se io che in da fanciullo dedicai me stesso alle Muse con ofſerir loro ciò che di
mano in mano mi venisse in virtù del loro divino concerto somministrato, lasciassi bora vedere il Decimo
parto de miei Madrigali, senza haver in fronte la dovuta loro protettione? Et quale poteva ella essere al
numero loro più propria, & a me loro facitore piu convenevole, che una Decima Musa, la quale & wivesse, 
& porgesse tuttavia a suoi devoti, & col commovimento, & con l'arte, spiriti rari, così di Musica, come di
Poesia, onde fosse bastante a farci salire alla più alta & incomprehensibile harmonia? Certo, che fra
quante hoggidì risplendono gloriose, niun'altra poteva essere giudicata più degna del nome di Musa, & insieme
d'Angelo celeste in terra, che V. Sig. Illustriss. poi ch'ella vince le nove sorelle, altretanto nelle loro proprie
arti, & discipline, quanto nelle bellezze, & ornamenti delle virtù così dell'animo, come del corpo. Dunque io per la grandezza
del singolar merito & valore di V. Sig. Illustriss. per l'antico debito del mio voto, & per la particolar inclinatione della mia
continua osservanza, consacro al suo fortunato Nome queste poche mie Note, sicuro che quello come celebratissimo renderà queste
altrui non men famose che grate, & fra tanto col raccomandare me stesso di tutto core alla sempre desiderata gratia di V. S. Illustriss. 
le prego da Dio tanta vittoria contro le ingiurie del tempo, quanta basti per eternarla in terra, & per bearla in Cielo.

Di Venetia alli 10. Settembre 1591.

Di V. S. Illustrissima

Affettionatissimo Servitore

Giaches Wert.
