= ALL'ILLUSTRISS. SIGNOR

== IL SIG. GIACOMO FUCCARI, SENIORI,

=== BARON DE CHIRCHBERG, ET WEISSENHORN, &C. 

==== Mio Signore, & Padrone Colendissimo.

Se Messer Andrea Gabrieli (felice memoria) non fosse stato mio Zio,
ardirei di dire (senza timore d'essere biasimato) che, si come pochi
Illustri Pittori, & Scultori insieme sono stati al mondo, così
pochissimi fossero stati gli eccellenti Compositori, & Organisti,
com'egli fu. Ma perché di consanguinità le sono poco meno che
figliuolo, non si conviene dir di lui liberamente quello, che 
l'affettione dettata dal vero mi ministrarebbe: perché, chi può
negare, che non sia stato mirabile, & quasi Divino in tutti i generi
Armonici? potrei lo darlo nell'arte, nelle rare inventioni, nelle maniere
nove, nel dilettevole stile, non solamente perché sia stato grave, &
dotto nelle sue compositioni, ma per esser insieme comparso tanto vago, &
leggiadro, che chi ha gustato il suono de' suoi concenti, & l'Armonia
de suoi contrapunti, (e vaglia dir il vero) può dire d'hauer provato
che cosa siano i veri movimenti di affetti, & che cosa sia goder della
Musica vera, & inusitata dolcezza; Potrei dire, che da suoi componimenti
si vede apertamente quanto egli sia stato singulare nell'immitatione in
ritrovar suoni esprimenti l'Energia delle parole e de' concetti, Ma per
non parer trabocchevole nel colmo dell'affettione, essendogli io Nipote,
lasciarò il farne giuditio a gli intendenti che l'hanno conosciuto sin
nell'interno ricetto de suoi pensieri. Piacque al sommo voler di Dio l'anno
passato di trasferirlo di terra in Paradiso, in età matura si,
& assai colma d' anni, ma in tempo che più che mai i spiriti erano
nella Musica vivaci e pieni di leggiadrissime inventioni. Haveva esso
ridotto a compita perfettione varaii bellissimi Concerti, Dialoghi, &
altre Musiche proportionate a voci, & stromenti, come hoggidì s'usa
nelle principali Chiese de Principi, & nelle Academie Illustri; de quali
egli (bona memoria) havea deliberato farne dono a V.S. Illustriss. per
scoprirle un vivo segno dell'osservanza & devotione che le portava. Ma
chiamato a miglior vita, il desiderio non ebbe il suo fine: ma si
come lasciò me herede de suoi beni esterni, così de' beni interni
(oltre gli amaestramenti della Musica) mi lasciò quella particolar
affettuosa devotione ch'esso portava à V. S. Illustriss. Onde vivendo
io con l'istesso desiderio co'l quale egli visse & morì, per essequir
il suo volere, & per dar compita satisfattione a me medesimo, consacro
à V.S. Illustriss. i frutti delle sue virtù intitolati i Concerti,
con l'aggiunta d'alcune mie fatiche, come virgulti germolianti dell'istesso
tronco. A lei li espongo come à vivificante Sole, da i cui
raggi prendendo vigore di pregio & di valore, non è dubbio che dal
mondo saranno bramati e tenuti cari. Piaccia a quella generosità d'animo
Heroico di humanamente gradirli, che assicurato io di questo,
mi terrò aventuroso, havendo fatto un si ricco acquisto, d' havermi
reso grato un tal Signore, la fama splendidissima del quale, con supremi
honori, & con ali d' immortalità volando, trascorre sin alle finitime
parti della terra. Con questo fine con ogni riverenza, humilmente bacio
le mani a V. S. Illustriss. pregandole da N. S. felice vita, & successo
de suoi alti, & generosi pensieri.

Di V.S. Illustriss. 

Humiliss. Servitore

Gioanni [sic] Gabrieli.
