= AL REVERENDISSIMO ET HONORATISSIMO

== MONSIGNOR DOMENICO PARUTA,

=== Dignissimo Abbate di Santo Gregorio, mio Signore.

Io non doveva ne poteva Reverendissimo Signor mio publicare queste mie nuove
fatiche al mondo, farle veder sotto altro più chiaro nome che il suo: percio che quanto al debito
mio: essendo V.S.R. singulariss. protettor & amatore delle virtu, & spetialmente della Musica 
tanto lodata & esltata del Divino Platone, Io non doveva ne debbo mandar ad altri
queste mie fatiche ch'alei, attento ch'll fa gradire chi l'ama & chi la honora di tutto cuore,
come faccio io. Quanto al potere: Io non vedeva (& cio sia detto con la bocca del vero) chi più meritasse 
di lei percio che ogn'un sa come ella nobiliss. & cortessissimo Prelato, ha pochi pari in bontà
d'animo, & di costumi, e come meritissimo d'ogni grado vive con degnita convenevole,
que con quell'animo ch'io le porgo le presenti fatiche, accettarle che a me basta assai di haver
sodisfatto a me stesso, mentre che servendo cosi raro Signore: pensero d'essergli in gratia e li
bascio le mani.

D.V.S.R.

Humilissimo servitore Andrea Gabrieli
