= ALLA SERENISS. SIGN.

== PATRONA MIA COLLENDISS.

=== LA GRAN DUCHESSA DI TOSCANA.

Quanti beni, et perfettioni, V. A. ha insemedesma
ond'ella non ha bisogno di cosa alcuna
fuor di se per dilettarsi, o giovarsi, tante
cagioni ho io di bramar la gratia, e protesstione,
e favor sua: Per il che non devrà
prender maraviglia, s'hora con ogni riverenza,
& humiltà  vengo a dedicarle questa
mia fatiga, qual ella sia, accio che dal suo glorioso nome, e da suoi
raggi quel decoro aquisti, e quello splendore, che per se stessa le
manca. Ne per che la divota servitù mia sia tardata fin qui a ve
nirle in cognitione, Confido io punto meno, o spero l'effetto del mio
desiderio, per ciò che voglio credere, che V. A. con la generosità
del animo suo si degnarà suplire alla picciolezza del dono, e grto
dalla detta prottetione sua potrò con l'ocio tranquillo concessome
dalla benignità dell'Illustrissimo & Reverendiss. Cardinale
d'Este mio Signore applicar l'animo ad opre più degne per farmi
ancor più degno, e capace del favor suo, di che quanto posso humilmente
prego, e supplico. V. A. a cui con ogni riverenza me inchino
a bacio la mano,

Di Roma alla 12. di Febraro 1585.

Di Vostra Altezza.

Humiliss. & devotiss. servitore.

Luca Marenzio.
