= AL MOLTO ILLUSTRE SIGNOR MIO OSSERVANDISS

== IL SIGNOR CONTE MARCO VERITA.

Se la povera mia fortuna non mi concede, ch'io possa con qualche degna ricompensa
mostrarmi grato a V. Sig. delle tante cortesie, che ella m'ha fatte mi sforzo almeno di
supplire con una continua affettione, la quale non lascia mancare in me il desiderio, c'ho di
servirla, e di far fede al mondo quanto io le sia tenuto. Et perche non posso con la sola voce mia
far bene espressa la grandezza di questo obligo, mi è parso di mandare in luce sotto
l'honorato nome di V. Sig. i presenti miei primi Madrigali a Cinque voci, accio che habbiano
a servire per una maggiore espressione. V. Sig. dunque si degnerà d'accettarli per una
semplice riconoscenza de favori, c'hò ricevuti da lei, con renderla certa, che per questo solo
rispetto io gli lascio venire al cospetto de gli huomini, e non perche io pretenda con essi d'acquistare a lei & a me
alcuno honore; per che ella è illustrata in modo dalle sue virtù, che non hà bisogno dell'altrui splendore ; & io non
devo aspettare di compositioni cosi giovenili, come son queste mie, altra lode, che quella che si suole dare ai
fiori di Primavera, in rispetto di quella che si dà ai frutti dell'Esta e dell'Auttunno. Con che facendo fine a V. Sig.
bacio le mani. Di Cremona il dì 27. Genaro. 1587.

Di V. Sig. molto Illustre

Servitore obligatissimo

Claudio Monteverde.
