= To the Virtuous Readers

Like a skilled hand retouching well-tuned strings makes wonderful harmony;
so we likewise hope for the Madrigals of this DRY LAUREL, collected by us with
exquisite diligence from the most Excellent Composers of Italy, and now
printed and to you dedicated; if these will by your grace be found worthy,
accompanied by your voices [_singers_], they may with their harmony reveal themselves
meritous of your protection, and we, who are their [_the madrigals--ed._] fathers, 
because we have until now restrained our affection for them, waiting that they
be measured by your infallible judgement: Under your judicious, but kindly
discernment; we will shortly present another selection of Madrigals,
composed about a new and green Laurel, from whose precious and fresh
roots one can expect ripe and most sweet fruits, these, if any of these
be picked improvidently, remain sour, [_but_] they will undoubtedly ripen into the
sweetest apple of Music. Meanwhile, confiding in pure and sincere 
intentions, in order to avoid the bite of jealousy, we have not wanted to
conceal it from the protection of any Prince, as be the custom for work these
days, more so because we do not long for any other reward for our labors
than your unversal beneficent grace, into which we commend ourselves.

THE RENEWED.
