= A' virtuosi Lettori.

Come dotta mano ritoccando ben temprate corde fà mirabil
concento; così parimente speriamo noi, che i Madrigali di 
questo SECCO LAURO da noi con esquisita diligenza dai più
Eccellenti Compositori d'Italia raccolti, et hora stampati, et a
voi dedicati; se fien mercè vostra fatti degni che si
accompagnino con le vostre voci, potran con la lor' armonia scoprir
se stessi meritevoli della vostra protettione, et noi, che padri lor
siamo, per giusti giudici, poi che fin hora habbiamo raffrenata l'affettione
nostra verso di loro, aspettando che sia misurata dall' infallibil
giuditio vostro: sotto alla cui giudiciosa, ma benigna censura; di
corto porremo un' altra scielta di Madrigali, composti sopra un nuovo
et verde Lauro, dalle cui pregiate et fresche radici non si posson'
aspettare che maturi et dolcissimi frutti, de' quali, se alcuno per esser
intempestivamente colto restasse acerbetto, sarà indubitatamente condito
nel soavissimo mele della Musica. In tanto noi confidati nella candida et
sincera intentione, per fuggir il morso degl'invidi, non la abbiamo voluto
ammantarsi della protettione di alcun Prencipe, come ricerca il costume d'
hoggidì, tanto più che non bramiamo altro premio della nostra fatica
che la buona vostra universal gratia; in cui ci raccomandiamo.

I RINOVATI.

