= ALLA SERENISSIMA SIGNORA MARGHERITA FARNESA

== GONZAGA PRENCIPESSA DI MANTOVA ETC.

Desiderando io di dedicare questi miei Madrigali a Patrone corrispondente, & intendendo
che V.A. fra l'altre nobilissime virtù di che viene adorna, possede benissimo questa della
Musica, del cui honoratissimo trattenimento resta anco non poco invaghita, vengo ad 
appoggiarli sopra l'altezza della virtù & autorità sua, non solamente per alzarli co'l suo favore
& merito a quel grado, che da se non ponno meritare, ma anco perché non si tosto
escano di fiore, perciò che rendomi sicuro, che riposti all'ombra di lei non mancherà
loro qualità di coprirgli, affinche almeno per molto tempo non seccandosi, serbino quel poco
d'odore, che loro apporta la novella prodottione di questo tempo di Primauera, in che 
holli dal mio povero giardino raccolti. Se ne escono dunque al suo raro ingegno consacrati, & da me seguiti
a supplicare V.A. che si degni di accettarli per un picciolo segno della mia servitù, tenendo per fermo, che mi
doglio di mia sorte, che m'habbia fatto si humile, & priuo, che con maggior effetto non possa mostrarle la
servitù della divotione mia, ma che però supplirà sempre la fede, & l'intentione con ogni affetto, di cui hora
le chiedo in gratia, che riceva quest'opra con quell' humanità, che non meno che l'altre virtù, la rende degna
d'ogni ammiratione, & ovunque fa ribombare il nome suo. Et qui a V.A. faccio humile riverenza, & insieme priego
quella felicità, ch'essa desidera & merita. Di Mantoua il dì 10 di Aprile. 1581.

Di V. A.

Devotissimo Servitore

Giaches Wert.
