    composer = "Claude le Jeune (c.1528-1600)"
    folio = "Antoine de la Roche Chandieu (1534-1591)"
    source = \markup { \italic { Octonaires de la vanite et inconstance du monde } (Ballard press, Paris, 1606) }
    style = "Renaissance"
    maintainer = "Allen Garvin"
    maintainerEmail = "allen.garvin@aurvondel.com"
    maintainerWeb = "http://blog.nitfol.com"
    booktitle = \markup { Typeset by Allen Garvin (aurvondel@gmail.com) (ver. #(strftime "%Y-%m-%d)" (localtime (current-time))) CC BY-NC 2.5 }
    tagline = #'f
