= AL MOLTO ILLUSTRE SIG.

== IL S. ALFONSO GONZAGA,

=== CONTE DI NUVOLARA MIO SIGNORE

==== E PADRONE OSSERVANDISSIMO.


Tanta è la seruitù e l'obligo, molto Illustre Sig. mio, che io tengo
con V. S. che mi parrebbe di mancar grandemente al debito di buon
servitore, e di fedel suddito, come a lei sono, se con ogni industria
& ogni poter mio, quantunque poco e debole, non procacciaffi
di mostrarle alcun segno della mia seruitù e divotione. Onde dovendo
hora questi miei Madrigali uscire in luce, ho voluto mandarli, benché
indegni del perfetto giudicio di V.S. Illustre, sotto il suo chiarissimo
nome, per esser quello veramente Illustre, Non solo per l'antica nobiltà della casa sua,
e de gl'Illuftrissimi & valorosissimi predecessori suoi, ma perché ella ancora è di così fatta
arte e, di tante altre rare virtù adorna, che da tutti meritamente vien giudicata albergo
delle Muse, & esempio d'ogni valore: Senza che col suo scudo saranno queste mie fatiche
per giovanili, (ch'elle siano) difese da morsi de' detrattori. Piacerà adunque a V.S. poi
che io non posso donarle cosa eguale al debito & al desiderio mio, d'accettar questo mio 
picciol dono, che sono i primi frutti del mio poco colto giardino . Ilche facendo, mi
porgerà animo di far, ch'ella nell'avenire gusti di quello più maturi & aggradevoli frutti:
e conoscerà il mondo, quanto son ricordevole e desideroso di gradire i molti benefici
e favori per me ricevuti dalla sua liberalissima cortesia. Allaquale riverentemente
bascio le mani. 

Di. V. S. Illustru.

Divotiss. servitore Giaches de Wert.
