= TO HIS MOST ILLUSTRIOUS LORDSHIP

== ALFONSO GONZAGA,

=== MY LORD, COUNT OF NUVOLARA

==== AND MOST OBSERVANT PATRON

Such is the servitude and obligation, Most Illustrious Sir, which I hold
for you that it would seem to me to be greatly neglecting my duty as
a good servant and a loyal subjects, as I am to you, if with every effort
and every power of mine, however small and weak, I did not try to demonstrate
some sign of my service and devotion to you. Therefore, as these 
Madrigals of mine must needs be published, I wanted to them, even as
they are unworthy of the esteemed judgment of your Illustrious Lordship,
under your brightest name, it is truly prestigious, not only for the
ancient nobility of your House, and of your illustrious and valorous
predecessors, but because you moreover are gifted with remarkable talent
and adorned with so many other rare virtues, that you are judged by all
as a sanctuary of the Muses and a paragon of every valor: without your
protection these efforts of mine, youthful (that they be), will be
protected from the biting attacks of detractors. Thus, Your Lordship
will be pleased, as I cannot gift to you anything equal to my obligation
and desire, should you accept this small token, which are the first
fruits cultivated in my small garden. In doing so, you will grant me
the courage to ensure that in the future, you might savor from that
more mature and pleasing fruits: and the world will know, how much
I revere and desire to enjoy the many benefits and favors I have
received from your boundless generosity. To which I reverently kiss your
hands.

Your Illustrious Lordship's

Devoted servant, Giaches de Wert


