= ALL'ILLUSTRISS. ET REVERENISS. SIGNOR

== ET PATRON MIO SEMPRE COLENDISSIMO.

=== IL SIGNOR CARDINALE D'ESTE

Io non prosume tanto di me, ne sono così poco conoscitore dell'imperfettione di queste
mie fatiche, che presentandole à V. S. Illustrissima m'imagini di offerirle cosa non indesgna
di lei; ma essendo io fatto suo non solamente per obligo di servitù, ma per elettione
di volontà, e per debito di infiniti favori ricevuti senz'alcun merito mio dalla sua singolar
cortesia, vengo à sodisfarle (se non come debbo almen come posto) quel segno che son
tenuto darli per tanti rispetti. Degnifi V. S. Illustrissima di gradire con l'usata sua benignità
questa prontezza dell'animo mio, & contentisi che dal'lume della grandezza sua prendano
queste mie primitie quello spirito, che non hà potuto lor dare il mio poco intelletto.
Con che humilissimamente la bacio la mano, & li prego ogni desiderata felicità. Di Roma il di 8. Agosto 1580.

Di V. S. Illustrissima & Reverendissima

Humiliss, & obligatiss. Servitore

Luca Marentio.
