= ALL'ILLUSTRISS.mo ET ECCELL.mo S.r

== IL S. OTTAVIO FARNESE

=== Duca di Parma & Piacenza, mio S. osservandiss.

Son Stato non poco pensoso, Illstriss. & Eccellentiss Signor mio, ritrovandomi tanto obligato
alla cortesia & benignità sua grandissima, considerando che dove cercar potessi da
una parte fuggire l'odioso nome di ingrato, non mi fusse da l'altra parte giudicata per cosa
leggiere, & temeraria il donar' a V. Eccellenza cosa de sì poco momento, in ricompensa de
cotanti singulari beneficii, & grandi honori riceputi dalla ineffabil cortesia, & benignità
sua, a non essersi sdegnata di tenerme un mio figliuolo a battesimo, con ogni amorevolissima
dimostratione. Ma si come fu sempre cosa, appo tutti buoni laudatissima, il fuggire
l'ingratitudine, facendo almeno segno per quanto dalla benignità de cieli all'huomo vien
concesso, con quel poco ch'è nel poter suo, piu tosto che tacendo, mostrare a non tenerne
conto, ne memoria; mi son risoluto di donarle & lasciar uscire sotto l'Illustriss &
felicissimo nome suo, questi miei madrigali, che hora vengono in luce; il qual dono (benché sia
minimo, rispetto gl'infiniti oblighi che tengo verso di lei) son certo che secondo la innata sua
cortesia, & singular generosità del nobilissimo animo suo, havera piu tosto riguardo, al
desiderio mio grandissimo che ho di honorarla, che al valore di questo mio così piccolo dono.
Ho preso adonque ardire di praesentarle queste, tali quali elle si sieno, fatiche mie, pregandola
humilmente, che ricompensando ogni lor mancamento, con la sincerità del desiderio &
affettion mia, benignamente le riceva, insieme con l'animo mio devotissimo (secondo il poco
poter mio) di servirla & honorarla sempre, alla quale con ogni riverenza inchinandome bascio
le mani, pregando l'Eterno Iddio, che con somma felicità & contento, ogni suo desiderio
perpetuamente prosperi & adempi. 

Di V. Eccellenza divotiss servidore. 

Giaches de Wert.
