= AL SERENISSIMO

== SIGNOR DUCA DI MANTOA

=== ET DI MONFERATO &c.

Gravissimo dolore io ricevi Sereniss. Sig. non essendomi trovato
in Corregio quando all'Altezza V. piacque di honorar questa
Città con la sua preferenza, perché con quell'occasione, potevo
pur una volta effettuare quello che già buon tempo fa, ardentemente
ho desiderato, ch'è di scoprirmele per quel devoto Servitore
ch'io li sono sempre stato da che hebbi alcuna cognitione
della magnamimità dell'animo di lei, & delle Heroiche virtù delle
quali ella è così riccamente adornata. Ma essendomi poi riferto
la singolar gratia fattami da V.A. d'udir benignamente, & con qualche diletto
parte della mia Musica, come ella si contentò di darne segno co'l commettere
che glieve
fosse inviato, ha non solo temprato il  mio dolore, ma portomi questa occasione di
offerirlemi Servitore devotissimo col pensiero che in me è nato di dedicarle questi
miei Madrigali; disegual dono in vero alla grandezza di lei: Ma si come ardirano col
Serenissimo nome di V.A. in fronte, comparire nel teatro del mondo: Così con la
scorta della sincerissima mia devotione, spero saranno fatti degni d'essere accerttati
tanto prontamente quanto benignamente furono uditi. Con che humilissimamente
inchinandomi, bacio a V.A. le mani, e prego il Signor Iddio, che li dia quel colmo di
grandezza, & di felicità, ch'ella stessa desidera.

Di Corregigio il 20. Novemb 1589.

Di V.A. Sereniss.

Devotiss. Servitore

Horatio Vecchi
