= Francesco Petrarca (1304-1374)

One of the _tre corone_ of Italian literature, and the most famous lyric
poet of European history, Petrarch (the usual rendering in English)
 was the single-most used poetic source
for the cinquecento madrigale. Thousands of settings exist, primarily
starting in the 1540s and lasting well into the 17th century. 

His primary work was the _Rerum vulgarium fragmenta_
("Fragments of Vernacular Matters"), also known as his _Canzoniere_, and
sometimes as the _Rime Sparse_ ("Scattered rhymes", taken from the first
poem of the work). The 366 poems consist of 317 sonetti (sonnets), 19 canzoni, 9
sestine, 7 ballate, and 4 madrigali. It was begun in 1327, and continued
through most of Petrarch's life, ending around 1368. An autograph copy in
the Vatican provides dating for most of the pieces. The central theme is
the poet's love for Laura, whom Petrarch met in April 1327. There are many
puns on Laura's name, mostly _l'aura_ (breeze, sometimes aura) or
_lauro_ (laurel, the tree associated with Apollo, and poetry since classical 
times). The first 263 poems are traditional classified as "In vita", written
during the life of Laura, and the remaining 103 "In morte", after her death.

In the late 1400s Pietro Bembo (1470-1547) gained a love of the Florentine
dialect while his father served as an ambassador for Venice in Florence,
and especially a love of the poetry of Petrarch. In the early 1500s, he
wrote a work that came to be known as the _Prose della volgar lingua_
(Prose of the Vernacular Tongue), which circulated widely in literary
circles in manuscript form before being published in 1525. It extolled
Petrarch as the best example of Italian poetry (and Boccaccio for prose).
He also edited the first truly authentic edition of Petrarch's poetry in
the age of the printing press. More than any thing else, this established
Petrarch as the model for poetry, and started a century-long trend of 
Petrarcan poetry widely imitated by poets throughout the peninsula.

The musical madrigal began its life in 1520s Florence, and was more associated
with somewhat lighter forms of poetry, mostly (of course) the madrigal,
with its unfixed rhyme scheme (which by this time allowed 7-syllable lines
as well as 11-syllable: the four examples in the Canzoniere only consist
of hendecasyllabic lines). Early settings of Petrarch exist, including
Verdelot's famous setting of _Italia Mia_ (#128), but it was not until
the 1540s as the madrigal became more widespread outside of Florence that
Petrarch was widely used as a model. Cipriano de Rore and Adriano Willaert,
especially, associated with Venice and Ferrara, set many sonnets of Petrarch, 
usually 6-part pieces. Willaert's famous publication, the _Musica Nova_ of 
1559, consisted of 21 sonnets of Petrarch (most written years past and
only circulated in manuscript). Toward the end of the century, the popularity
of Petrarcan poetry began to wane, especially as pastoral poetry 
experienced a sudden vogue around 1570-1600, though it never disappeared
entirely.

Madrigal prints of the seicento containing at least one text from the _Canzoniere_, with the
number of such pieces:
[width="80%",cols="<5,>1,>2,>3,>4,>5",frame="topbot",options="header,footer"]
|==========================
|Decade        | Collections |  Pieces | Avg. per Col. | Avg. per decade | Avg. annual
|1520-1529     | 2           | 10      | 5             | 0.2             | 1
|1530-1539     | 11          | 30      | 2.7           | 1.1             | 3
|1540-1549     | 61          | 367     | 6             | 6.1             | 36.7
|1550-1559     | 61          | 368     | 6             | 6.1             | 36.8
|1560-1569     | 122         | 746     | 6.1           | 12.2            | 74.6
|1570-1579     | 91          | 379     | 4.1           | 9.1             | 37.6
|1580-1589     | 111         | 438     | 3.9           | 11.1            | 43.8
|1590-1599     | 52          | 128     | 2.4           | 5.2             | 12.8
|Total         | 511         | 2466    | 4.8           | 6.4             | 30.8
|==========================

Source for table: Cecchi, Paolo. "La Fortuna Musicale Della 'Canzone Alla Vergine'." In _Petrarca in musica_, 
edited by Andrea Chegai and Cecilia Luzzi, pp. 247-291. Biblioteca Musicale LIM, 2006.



